FROM "mcr.microsoft.com/devcontainers/rust"

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get -y install --no-install-recommends \
  xorg \
  openbox \
  libnss3 \
  libasound2 \
  libatk-adaptor \
  libwebkit2gtk-4.0-dev \
  build-essential \
  curl \
  wget \
  libssl-dev \
  libgtk-3-dev \
  libayatana-appindicator3-dev \
  librsvg2-dev